name: add_song_name_to_PR

on:
  pull_request:
    types:
      - opened

jobs:
  add_song_name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Add Song Name
        run: |
          song_name="New Song Name"
          echo "New Song: $song_name" >> $(githubworkspace)/song_names.txt
          git add song_name.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHubAction"
          git commit -m "Add new song: $song_name" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}



